name: 'build and deploy production'

on:
  push:
    tags:
      - '*'

jobs:
  release-docker-image-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: npm i

      - name: build image and push to github packages
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
            image: ${{github.event.repository.name}}
            # tags: v1, latest
            registry: ghcr.io
            username: ${{ github.actor }}
            password: ${{ secrets.GITHUB_TOKEN }}

  